name: Text Transformer CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build and test with Maven
        run: mvn clean compile test package
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: "target/surefire-reports/**/*.xml"
      - name: Get version
        run: echo "VERSION=v$(mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Generate documentation
        if: github.ref == 'refs/heads/master'
        run: mvn javadoc:javadoc
      - name: Zip documentation
        if: github.ref == 'refs/heads/master'
        run: zip -r target/docs.zip target/site
      - name: Create tag
        if: github.ref == 'refs/heads/master'
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "${{ env.VERSION }}"
      - name: Release
        if: github.ref == 'refs/heads/master'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.VERSION }}"
          prerelease: false
          files: |
            README.md
            target/docs.zip
            target/*.jar
